package com.appfuxion.selenium.model;

public class ParamsObject {
	public final static String PARAM_TRACE_LOG = "TRUE";
	public final static String PARAM_ENABLE_LOG = "YES";
	public final static String PARAM_ON = "ON";
	public final static String PARAM_OFF = "OFF";
	public final static String PARAM_TEST_SCRIPT_SHEET = "TestScript";
	public final static String PARAM_TEST_DATA_SHEET = "TestData";
	public final static String CONFIG_General = "General";
	public final static String CONFIG_ABOUT = "ABOUT";
	public final static String CONFIG_DEFAULTPATH = "DEFAULTPATH";
	public final static String CONFIG_RECURSIVE = "RECURSIVE";
	public final static String CONFIG_PROJECT_NAME = "PROJECT_NAME";
	public final static String CONFIG_PLATFORM = "PLATFORM";
	public final static String CONFIG_WAIT_TIME = "WAIT_TIME";
	public final static String CONFIG_SYNC_TIMEOUT = "SYNC_TIMEOUT";
	public final static String CONFIG_OUTPUT_PATH = "OUTPUT_PATH";
	public final static String CONFIG_TRACE_LOG = "TRACE_LOG";
	public final static String CONFIG_GET_NOW = "GET_NOW";
	public final static String CONFIG_TEMPLATE_DOC = "TEMPLATE_DOC";
	public final static String CONFIG_TEMPLATE_HTML = "TEMPLATE_HTML";
	public final static String CONFIG_HIGHLIGHT_VERIFY_XLS = "HIGHLIGHT_VERIFY_XLS";
	public final static String CONFIG_CLOSE_BROWSER_AFTER_RUN = "CLOSE_BROWSER_AFTER_RUN";
	public final static String CONFIG_WAIT_OBJECT = "WAIT_OBJECT";
	public final static String CONFIG_Addins = "Addins";
	public final static String CONFIG_WEB = "WEB";
	public final static String CONFIG_MOBILE = "MOBILE";
	public final static String CONFIG_WIN = "WIN";
	public final static String CONFIG_TE = "TE";
	public final static String CONFIG_UIA = "UIA";
	public final static String CONFIG_VB = "VB";
	public final static String CONFIG_NET = "NET";
	public final static String CONFIG_SAP = "SAP";
	public final static String CONFIG_Report = "Report";
	public final static String CONFIG_WORD = "WORD";
	public final static String CONFIG_PDF = "PDF";
	public final static String CONFIG_EXCEL = "EXCEL";
	public final static String CONFIG_IMAGE = "IMAGE";
	public final static String CONFIG_Environment = "Environment";
	public final static String CONFIG_AS400_Maker_ID = "AS400_Maker_ID";
	public final static String CONFIG_AS400_Maker_Pass = "AS400_Maker_Pass";
	public final static String CONFIG_AS400_PATH = "AS400_PATH";
	public final static String CONFIG_Package_Name = "Package_Name";
	public final static String CONFIG_CAPTURE_DEVICE = "CAPTURE_DEVICE";
	public final static String CONFIG_ENABLE_LOG = "ENABLE_LOG";
	public final static String CONFIG_FORCE_SCREENSHOT = "FORCE_SCREENSHOT";
	public final static String CONFIG_Close_Browser = "Close_Browser";
	public final static String CONFIG_FieldNotExist = "FieldNotExist";
	public final static String CONFIG_IMPORT_SHEET = "IMPORT_SHEET";
	public final static String CONFIG_MessageChecker = "MessageChecker";
	public final static String CONFIG_MobileLaunchMethod = "MobileLaunchMethod";
	public final static String CONFIG_PDFTOTEXT_PATH = "PDFTOTEXT_PATH";
	public final static String CONFIG_REPORT_PATH = "REPORT_PATH";
	public final static String CONFIG_SMS_Path_File = "SMS_Path_File";	
	public final static String PARAM_DATE_YYYYMMDDHHMMSS = "yyyyMMddHHmmss";
	public final static String PARAM_LOG_FOLDER = "log";
	public final static String PARAM_LOG_EXTENSIONS = ".log";
	public final static String PARAM_HTML_EXTENSIONS = ".html";
	public final static String PARAM_PNG = "PNG";
	public final static String PARAM_PNG_EXTENSIONS = ".png";
	public final static String PARAM_XLS_EXTENSIONS = ".xlsx";
	public final static String PARAM_DOC_EXTENSIONS = ".doc";
	public final static String PARAM_DOCX_EXTENSIONS = ".docx";
	public final static String PARAM_PDF_EXTENSIONS = ".pdf";
	public final static String PARAM_TXT_EXTENSIONS = ".txt";
	public final static String PARAM_NEW_LINE = "\n";
	public final static String PARAM_DATE_YYYY_MM_DD_HH_MM_SS ="yyyy-MM-dd HH:mm:ss";
	public final static String PARAM_DATE_YYYY_MM_DD_HH_MM_SS_REPORT ="yyyy-MM-dd_HH-mm-ss";
	public final static String PARAM_DATE_MM_DD_YYYY = "MM/dd/yyyy";
	public final static String PARAM_DATE_HH_MM_SS = "HH:mm:ss";
	public final static String PARAM_Y = "Y";
	public final static String PARAM_YES = "YES";
	public final static String PARAM_FULL = "full";
	public final static String PARAM_UNIT_STEP = " Step";
	public final static String PARAM_UNIT_ROW = " Row";
	public final static String PARAM_UNIT_FINAL_TEST_SCRIPT = " FinalTestScript";
	public final static String PARAM_UNIT_TOTAL_TS_FILE = " TotalTestScriptFiles";
	public final static String PARAM_TC_ID = "TC_ID";
	public final static String PARAM_GUI_CSS = "striped-progress.css";
	public final static String PARAM_GUI_PROGRESS_LABEL = "  PROGRESS";
	public final static String PARAM_GUI_ACTION_LABEL = "        STOP        ";
	public final static String PARAM_GUI_PASSED_LABEL = "  PASSED : ";
	public final static String PARAM_GUI_FAILED_LABEL = "  FAILED : ";
	public final static String PARAM_HTM_PASSED_LABEL = "Passed";
	public final static String PARAM_HTM_FAILED_LABEL = "Failed";
	public final static String PARAM_CLOSE_ACTION = "CloseAction";
	public final static String PARAM_GUI_TITLE = "RUNNING";
	public final static String PARAM_GUI_PREPARING_TESTSCRIPT_LABEL = " PREPARING TESTSCRIPT...";
	public final static String PARAM_GUI_RUN_TESTSCRIPT_LABEL = " RUN TESTSCRIPT...";
	public final static String PARAM_GUI_RUN_LABEL = "    RUN : ";
	public final static String PARAM_GUI_TOTAL_LABEL = "  TOTAL : ";
	public final static String PARAM_ABOUT = "about";
	public final static String PARAM_OS_ARCHITECTURE = "os.arch";
	public final static String PARAM_OS_NAME = "os.name";
	public final static String PARAM_X86 = "x86";
	public final static String PARAM_PLATFORM_IE = "ie";
	public final static String PARAM_IE_EXE_DRIVER_32 = "lib/IEDriverServer32.exe";
	public final static String PARAM_IE_EXE_DRIVER_64 = "lib/IEDriverServer64.exe";
	public final static String PARAM_IE_SYSTEM_PROPERTIES = "webdriver.ie.driver";
	public final static String PARAM_PLATFORM_FIREFOX = "firefox";
	public final static String PARAM_FIREFOX_EXE_DRIVER_32 = "lib/geckodriver32.exe";
	public final static String PARAM_FIREFOX_EXE_DRIVER_64 = "lib/geckodriver64.exe";
	public final static String PARAM_FIREFOX_SYSTEM_PROPERTIES = "webdriver.gecko.driver";
	public final static String PARAM_PLATFORM_CHROME = "chrome";
	public final static String PARAM_CHROME_EXE_DRIVER = "lib/chromedriver.exe";
	public final static String PARAM_CHROME_SYSTEM_PROPERTIES = "webdriver.chrome.driver";
	public final static String PARAM_PLATFORM_EDGE = "edge";
	public final static String PARAM_EDGE_EXE_DRIVER = "lib/MicrosoftWebDriver.exe";
	public final static String PARAM_EDGE_SYSTEM_PROPERTIES = "webdriver.edge.driver";
	public final static String PARAM_PLATFORM_SAFARI = "safari";
	public final static String PARAM_OT_LINK = "link";
	public final static String PARAM_LOC_ID = "id:=";
	public final static String PARAM_LOC_NAME = "name:=";
	public final static String PARAM_LOC_CLASS = "class:=";
	public final static String PARAM_LOC_CSS = "cssselector:=";
	public final static String PARAM_LOC_LINKTEXT1 = "linktext:=";
	public final static String PARAM_LOC_LINKTEXT2 = "text:=";
	public final static String PARAM_LOC_IFRAME = "iframe:=";
	public final static String PARAM_LOC_PARTIALLINKTEXT = "partiallinktext:=";
	public final static String PARAM_LOC_TAGNAME = "tagname:=";
	public final static String PARAM_LOC_XPATH = "xpath:=";
	public final static String PARAM_ACTION_CLICK = "click";
	public final static String PARAM_ACTION_SET = "set";
	public final static String PARAM_ACTION_SELECT = "select";
	public final static String PARAM_ACTION_EQUAL = "equal";
	public final static String PARAM_ACTION_EXIST = "exist";
	public final static String PARAM_LOG_PASSED = "PASSED";
	public final static String PARAM_LOG_FAILED = "FAILED";
	public final static String PARAM_REPORT_PASSED = "PASS";
	public final static String PARAM_REPORT_FAILED = "FAIL";
	public final static String PARAM_HTM_PASSED = "PASSED";
	public final static String PARAM_HTM_FAILED = "FAILED";
	public final static String PARAM_REPORT_FOLDER_DOC = "DOC";
	public final static String PARAM_REPORT_FOLDER_HTM = "HTM";
	public final static String PARAM_REPORT_FOLDER_LOGS = "LOGS";
	public final static String PARAM_REPORT_FOLDER_PDF = "PDF";
	public final static String PARAM_REPORT_FOLDER_RPT = "RPT";
	public final static String PARAM_REPORT_FOLDER_SST = "SST";
	public final static String PARAM_REPORT_FOLDER_XLS = "XLS";
	public final static String CONFIG_REPORT_LOG_NAME = "report.log";
	public final static String CONFIG_REPORT_RPT_NAME = "sub.uft.rpt";
	public final static String CONFIG_REPORT_RPT_REPORT = "[REPORT]";
	public final static String CONFIG_REPORT_RPT_PROJECTNAME = "rptProjectName=";
	public final static String CONFIG_REPORT_RPT_EXEC_STATUS = "rptExecStatus=";
	public final static String CONFIG_REPORT_RPT_TESTSCRIPTID = "rptTestScriptId=";
	public final static String CONFIG_REPORT_RPT_PLATFORM = "rptPlatform=";
	public final static String CONFIG_REPORT_RPT_PATH = "rptTRPath=";
	public final static String CONFIG_REPORT_RPT_DATE = "rptDate=";
	public final static String CONFIG_REPORT_RPT_START_TIME = "rptStartTime=";
	public final static String CONFIG_REPORT_RPT_END_TIME = "rptEndTime=";
	public final static String CONFIG_REPORT_RPT_DURATION = "rptDuration=";
	public final static String CONFIG_REPORT_RPT_VERSION = "rptAppVersion=";
	public final static String CONFIG_REPORT_RPT_DURATION_HOURS = "hrs ";
	public final static String CONFIG_REPORT_RPT_DURATION_MINUTES = "mins ";
	public final static String CONFIG_REPORT_RPT_DURATION_SECONDS = "secs ";
	public final static String PARAM_HTM_SECONDS = "s";
	public final static String CONFIG_REPORT_XLS_SHEET_GLOBAL = "Global";
	public final static String CONFIG_REPORT_XLS_SHEET_GLOBAL_LABEL = "LABEL";
	public final static String CONFIG_REPORT_XLS_SHEET_GLOBAL_VALUE = "VALUE";
	public final static String CONFIG_REPORT_XLS_SHEET_GLOBAL_START_TIME = "START_TIME";
	public final static String CONFIG_REPORT_XLS_SHEET_GLOBAL_OUTPUT_PATH = "OUTPUT_PATH";
	public final static String CONFIG_REPORT_XLS_SHEET_GLOBAL_PROJECT_NAME = "Project Name";
	public final static String CONFIG_REPORT_XLS_SHEET_GLOBAL_TEST_SCRIPT_ID = "Test Script ID";
	public final static String CONFIG_REPORT_XLS_SHEET_GLOBAL_PLATFORM = "Platform";
	public final static String CONFIG_REPORT_XLS_SHEET_GLOBAL_APP_VERSION = "App Version";
	public final static String CONFIG_REPORT_XLS_SHEET_ACTION1 = "Action1";
	public final static String CONFIG_REPORT_XLS_SHEET_ACTION1_STEP_NAME = "Step_Name";
	public final static String CONFIG_REPORT_XLS_SHEET_ACTION1_OBJECT_TYPE = "Object_Type";
	public final static String CONFIG_REPORT_XLS_SHEET_ACTION1_OBJECT_ID = "Object_ID";
	public final static String CONFIG_REPORT_XLS_SHEET_ACTION1_OBJECT_FRAME = "Object_Frame";
	public final static String CONFIG_REPORT_XLS_SHEET_ACTION1_ACTION = "Action";
	public final static String CONFIG_REPORT_XLS_SHEET_ACTION1_TEST_DATA = "Test_Data";
	public final static String CONFIG_REPORT_XLS_SHEET_ACTION1_KEYWORD = "Keyword";
	public final static String CONFIG_REPORT_XLS_SHEET_ACTION1_APPLICATION_PATH = "Application_Path";
	public final static String CONFIG_REPORT_XLS_SHEET_ACTION1_DRIVER = "Driver";
	public final static String CONFIG_REPORT_XLS_SHEET_ACTION1_ENVIRONMENT = "Environment";
	public final static String CONFIG_REPORT_XLS_SHEET_ACTION1_DESCRIPTION = "Description";
	public final static String CONFIG_REPORT_XLS_SHEET_ACTION1_EXPECTED_RESULT = "Expected_Result";
	public final static String CONFIG_REPORT_XLS_SHEET_REPORT = "Report";
	public final static String CONFIG_REPORT_XLS_SHEET_REPORT_NO = "No";
	public final static String CONFIG_REPORT_XLS_SHEET_REPORT_TESTSTEP = "TestStep";
	public final static String CONFIG_REPORT_XLS_SHEET_REPORT_TESTDATA = "TestData";
	public final static String CONFIG_REPORT_XLS_SHEET_REPORT_EXPECTEDRESULT = "ExpectedResult";
	public final static String CONFIG_REPORT_XLS_SHEET_REPORT_KEYWORD = "Keyword";
	public final static String CONFIG_REPORT_XLS_SHEET_REPORT_STATUS = "Status";
	public final static String CONFIG_REPORT_XLS_SHEET_REPORT_TIME = "Time";
	public final static String CONFIG_REPORT_XLS_SHEET_REPORT_INDEX = "Index";
	public final static String PARAM_HTM_LABEL_SUCCESS = "success";
	public final static String PARAM_HTM_LABEL_DANGER = "danger";
	public final static String PARAM_DOC_FONT_FAMILY_CALIBRI = "Calibri";
	public final static int PARAM_DOC_FONT_SIZE_11 = 11;
	public final static String PARAM_DOC_COLOR_BLACK = "000000";
	public final static String PARAM_DOC_RUN_DATE = "Run Date";
	public final static String PARAM_DOC_RUN_STARTED = "Run Started";
	public final static String PARAM_DOC_RUN_ENDED = "Run Ended";
	public final static String PARAM_DOC_EXECUTION_TIME = "Execution Time";
	public final static String PARAM_DOC_EXECUTION_STATUS = "Execution Status";	
	public final static String PARAM_DOC_COLOR_GREEN = "00B050";
	public final static String PARAM_DOC_COLOR_RED = "FF0000";
	public final static String PARAM_DOC_TEST_STEP = "Test Step";
	public final static String PARAM_CB_DEFAULT = "Default";
	public final static String PARAM_CB_CLOSE_ALL = "Close All";
	public final static String PARAM_CB_CLOSE_ALL_EXCEPT_FIRST = "Close All Except First";
	public final static String PARAM_CB_CLOSE_ALL_EXCEPT_LAST = "Close All Except Last";
	public final static String PARAM_CB_CLOSE_LATEST = "Close Latest Browser";
	public final static String CONFIG_EDGE = "microsoftedge.exe";
	public final static String CONFIG_CHROME = "chrome.exe";
	public final static String CONFIG_IE = "iexplore.exe";
	public final static String CONFIG_FIREFOX = "firefox.exe";
	public final static String CONFIG_SAFARI = "safari.exe";
	public final static String CONFIG_TASKLIST_COMMAND = "tasklist.exe /v /fo csv /nh /fi \"IMAGENAME eq ";
	public final static String CONFIG_TASKLIST_COMMAND_KILL = "taskkill /F /PID ";
	public final static String KW_CONSTANT_VERIFY = "verify";
	public final static String KW_CONSTANT_DATA_WRITE = "data_write";
	public final static String KW_CONSTANT_DATA_READ = "data_read";
	public final static String KW_CONSTANT_DATA_READ_ATT_VAL = "data_read attr_val";
	public final static String KW_CONSTANT_ATTR_VAL = "attr_val";
	public final static String KW_CONSTANT_ADDREFERENCE = "addreference";
	public final static String KW_CONSTANT_IF = "cond_if";
	public final static String KW_CONSTANT_ELSE = "cond_else";
	public final static String KW_CONSTANT_END_IF = "cond_endif";
	public final static String KW_CONSTANT_TRUE = "true";
	public final static String KW_CONSTANT_FALSE = "false";
	public final static String KW_CONSTANT_CONDITION_EQUAL = "equal";
	public final static String KW_CONSTANT_CONDITION_NOT_EQUAL = "notequal";
	public final static String KW_CONSTANT_CONDITION_GREATER_THAN = "greaterthan";
	public final static String KW_CONSTANT_CONDITION_LESSER_THAN = "lesserthan";
	public final static String KW_CONSTANT_CONDITION_GREATER_THAN_EQUAL = "greaterthanequal";
	public final static String KW_CONSTANT_CONDITION_LESSER_THAN_EQUAL = "lesserthanequal";
	public final static String KW_CONSTANT_VERIFY_XLS_DOCX = "verify_xls_docx";
	public final static String KW_CONSTANT_VERIFY_XLS_TXT = "verify_xls_txt";
	public final static String KW_CONSTANT_CLEAN_INPUT = "cleaninput";
	public final static String KW_CONSTANT_CLOSE_POP_UP_WINDOW = "close_pop_up_window";
	public final static String KW_CONSTANT_CLOSE_NEW_TAB_WINDOW = "close_new_tab_window";
	public final static String KW_CONSTANT_ALERT_ACCEPT = "alert_accept";
	public final static String KW_CONSTANT_ALERT_DISMISS = "alert_dismiss";
	public final static String KW_CONSTANT_WAIT_MY_OBJECT = "wait_my_object";

	public final static String AT_CONSTANT_VALUE = "value";
	
	public final static String OT_CONSTANT_WEBEDIT = "webedit";
	public final static String OT_CONSTANT_WEBLIST = "weblist";
	public final static String OT_CONSTANT_WEBCHECKBOX = "webcheckbox";
	public final static String OT_CONSTANT_WEBRADIOGROUP = "webradiogroup";
	
	public final static String OT_CONSTANT_WEBEHCKBOX_ON = "clicked";
	public final static String OT_CONSTANT_WEBEHCKBOX_OFF = "unclicked";
	
	public final static String PARAM_TEMPLATE_APPFUXION = "appfuxion";
	public final static String PARAM_TEMPLATE_NH2 = "nh2";
	
	public final static String PARAM_REF = "#REF#";
	
	public final static String PARAM_DOCTO_EXE = "lib/docto.exe";
	
	public final static String DRV_APPIUM_ANDROID = "appiumdroid";
	public final static String ENV_URL = "url";
	public final static String ENV_APP = "app";
}
